name: Build and Release JAR with Ant

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0, v2.1, etc.

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  # Use Eclipse Temurin (AdoptOpenJDK)
          java-version: '8'       # Adjust to your project's Java version
          
      - name: Set JDK Home
        run: echo "JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))" >> $GITHUB_ENV

      - name: Build with Ant
        run: ant -Dplatforms.JDK_1.8_openjdk.home=$JAVA_HOME jar

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload JAR to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/SwingUndoRedo.jar  # Adjust based on your build output
          asset_name: SwingUndoRedo-${{ github.ref_name }}.jar
          asset_content_type: application/java-archive
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
